name: Test Docker image build

on:
  push:
    branches:
      - '!main'
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v7

      - name: Build Docker image
        uses: docker/build-push-action@v7
        with:
          push: false
